steps:
  # 1) Unit tests
  - name: 'python:3.11-slim'
    id: 'run unit tests'
    entrypoint: bash
    args:
      - -lc
      - |
        set -e
        python -V
        pip install -U pip
        # Runtime deps
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Dev/test deps (httpx needed by fastapi.testclient via starlette)
        if [ -f requirements-dev.txt ]; then
          pip install -r requirements-dev.txt
        else
          pip install pytest httpx
        fi
        PYTHONPATH=. pytest -q

  # 2) Build image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker build'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/manager-monitor:${_TAG}', '.']

  # 3) Push image (required so Cloud Run can pull it)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker push'
    args: ['push', 'gcr.io/$PROJECT_ID/manager-monitor:${_TAG}']

  # 4) Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy cloud run'
    args:
      - run
      - deploy
      - manager-monitor
      - --image=gcr.io/$PROJECT_ID/manager-monitor:${_TAG}
      - --region=${_REGION}
      - --allow-unauthenticated

substitutions:
  _TAG: 'latest'
  _REGION: 'australia-southeast2'

images:
- gcr.io/$PROJECT_ID/manager-monitor:${_TAG}

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
