steps:
  # 1) Unit tests
  - name: 'python:3.11-slim'
    entrypoint: bash
    args:
      - -lc
      - |
        pip install -r requirements.txt pytest
        PYTHONPATH=. pytest -q

  # 2) Build image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/manager-monitor:${_TAG}', '.']

  # 3) Push image (required so Cloud Run can pull it)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/manager-monitor:${_TAG}']

  # 4) Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - manager-monitor
      - --image=gcr.io/$PROJECT_ID/manager-monitor:${_TAG}
      - --region=${_REGION}
      - --allow-unauthenticated

substitutions:
  _TAG: 'latest'
  _REGION: 'australia-southeast2'

# Optional: push metadata for the image
images:
- gcr.io/$PROJECT_ID/manager-monitor:${_TAG}

timeout: '1200s'
